/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dymoo6791
 */
public class Page1 extends javax.swing.JFrame {

    /**
     * Creates new form Page1
     */
    public Page1() {
        initComponents();
    }
    int counterCorrect = 0;
    int incorrectCounter = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        correctLbl = new javax.swing.JLabel();
        userInput1 = new javax.swing.JSpinner();
        outcomeLbl1 = new javax.swing.JLabel();
        CheckBtn = new javax.swing.JButton();
        incorrectLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        outcomeLbl2 = new javax.swing.JLabel();
        option1Btn = new javax.swing.JButton();
        option3Btn = new javax.swing.JButton();
        option2Btn = new javax.swing.JButton();
        option4Btn = new javax.swing.JButton();
        option1Btn1 = new javax.swing.JButton();
        option3Btn1 = new javax.swing.JButton();
        option4Btn1 = new javax.swing.JButton();
        option2Btn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        outcomeLbl3 = new javax.swing.JLabel();
        outcomeLbl4 = new javax.swing.JLabel();
        option1Btn2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        option3Btn2 = new javax.swing.JButton();
        option2Btn2 = new javax.swing.JButton();
        option4Btn2 = new javax.swing.JButton();
        option3Btn3 = new javax.swing.JButton();
        option1Btn3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        option2Btn3 = new javax.swing.JButton();
        option4Btn3 = new javax.swing.JButton();
        outcomeLbl5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Multiple Choice Quiz");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("How many math operators are used in programming?");

        correctLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        correctLbl.setText("0");

        userInput1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CheckBtn.setText("Check");
        CheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBtnActionPerformed(evt);
            }
        });

        incorrectLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        incorrectLbl.setText("0");

        jLabel3.setText("Correct:");

        jLabel4.setText("Incorrect:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Q2");

        option1Btn.setText("Option 1");
        option1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1BtnActionPerformed(evt);
            }
        });

        option3Btn.setText("Option 3");
        option3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3BtnActionPerformed(evt);
            }
        });

        option2Btn.setText("Option 2");
        option2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2BtnActionPerformed(evt);
            }
        });

        option4Btn.setText("Option 4");
        option4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4BtnActionPerformed(evt);
            }
        });

        option1Btn1.setText("Option 1");
        option1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1Btn1ActionPerformed(evt);
            }
        });

        option3Btn1.setText("Option 3");
        option3Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3Btn1ActionPerformed(evt);
            }
        });

        option4Btn1.setText("Option 4");
        option4Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4Btn1ActionPerformed(evt);
            }
        });

        option2Btn1.setText("Option 2");
        option2Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2Btn1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Q3");

        option1Btn2.setText("Option 1");
        option1Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1Btn2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Q4");

        option3Btn2.setText("Option 3");
        option3Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3Btn2ActionPerformed(evt);
            }
        });

        option2Btn2.setText("Option 2");
        option2Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2Btn2ActionPerformed(evt);
            }
        });

        option4Btn2.setText("Option 4");
        option4Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4Btn2ActionPerformed(evt);
            }
        });

        option3Btn3.setText("Option 3");
        option3Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3Btn3ActionPerformed(evt);
            }
        });

        option1Btn3.setText("Option 1");
        option1Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1Btn3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Q5");

        option2Btn3.setText("Option 2");
        option2Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2Btn3ActionPerformed(evt);
            }
        });

        option4Btn3.setText("Option 4");
        option4Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4Btn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(outcomeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(correctLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(incorrectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(option3Btn)
                                    .addGap(119, 119, 119)
                                    .addComponent(option4Btn))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(option1Btn)
                                    .addGap(119, 119, 119)
                                    .addComponent(option2Btn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(option3Btn1)
                                    .addGap(119, 119, 119)
                                    .addComponent(option4Btn1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(option1Btn1)
                                    .addGap(119, 119, 119)
                                    .addComponent(option2Btn1)))
                            .addComponent(jLabel6))
                        .addGap(283, 283, 283))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outcomeLbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(userInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outcomeLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(364, 364, 364))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(option3Btn2)
                                    .addGap(119, 119, 119)
                                    .addComponent(option4Btn2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(option1Btn2)
                                    .addGap(119, 119, 119)
                                    .addComponent(option2Btn2)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outcomeLbl4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(option3Btn3)
                                    .addGap(119, 119, 119)
                                    .addComponent(option4Btn3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(option1Btn3)
                                    .addGap(119, 119, 119)
                                    .addComponent(option2Btn3)))
                            .addComponent(jLabel8)
                            .addComponent(outcomeLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(283, 283, 283))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incorrectLbl)
                            .addComponent(correctLbl))
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addComponent(outcomeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option1Btn1)
                            .addComponent(option2Btn1)
                            .addComponent(option2Btn)
                            .addComponent(option1Btn))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option3Btn1)
                            .addComponent(option4Btn1)
                            .addComponent(option4Btn)
                            .addComponent(option3Btn))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outcomeLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outcomeLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option1Btn2)
                            .addComponent(option2Btn2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option3Btn2)
                            .addComponent(option4Btn2))
                        .addGap(18, 18, 18)
                        .addComponent(outcomeLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option1Btn3)
                            .addComponent(option2Btn3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option3Btn3)
                            .addComponent(option4Btn3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(outcomeLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBtnActionPerformed
        
        int Q1 = (Integer) userInput1.getValue();

        if (Q1 == 5) {
            outcomeLbl1.setText("Correct");
            counterCorrect = counterCorrect + 1;
            correctLbl.setText(String.valueOf(counterCorrect));
        } else {
            outcomeLbl1.setText("Incorrect, try again");
            incorrectCounter = incorrectCounter + 1;
            incorrectLbl.setText(String.valueOf(incorrectCounter));
        }
    }//GEN-LAST:event_CheckBtnActionPerformed

    private void option1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1BtnActionPerformed

        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl2.setText("Incorrect, try again");
    }//GEN-LAST:event_option1BtnActionPerformed

    private void option2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2BtnActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
outcomeLbl2.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option2BtnActionPerformed

    private void option4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4BtnActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl2.setText("Incorrect, try again");
    }//GEN-LAST:event_option4BtnActionPerformed

    private void option3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3BtnActionPerformed
        counterCorrect = counterCorrect + 1;
        correctLbl.setText(String.valueOf(counterCorrect));
        outcomeLbl2.setText("Correct");
    }//GEN-LAST:event_option3BtnActionPerformed

    private void option1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1Btn1ActionPerformed
        counterCorrect = counterCorrect + 1;
        correctLbl.setText(String.valueOf(counterCorrect));
        outcomeLbl3.setText("Correct");// TODO add your handling code here:
    }//GEN-LAST:event_option1Btn1ActionPerformed

    private void option3Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3Btn1ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl3.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option3Btn1ActionPerformed

    private void option4Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4Btn1ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl3.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option4Btn1ActionPerformed

    private void option2Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2Btn1ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl3.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option2Btn1ActionPerformed

    private void option1Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1Btn2ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter)); 
        outcomeLbl4.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option1Btn2ActionPerformed

    private void option3Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3Btn2ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter)); 
        outcomeLbl4.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option3Btn2ActionPerformed

    private void option2Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2Btn2ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl4.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option2Btn2ActionPerformed

    private void option4Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4Btn2ActionPerformed
        counterCorrect = counterCorrect + 1;
        correctLbl.setText(String.valueOf(counterCorrect));
        outcomeLbl4.setText("Correct");// TODO add your handling code here:  // TODO add your handling code here:
    }//GEN-LAST:event_option4Btn2ActionPerformed

    private void option3Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3Btn3ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl5.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option3Btn3ActionPerformed

    private void option1Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1Btn3ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl5.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option1Btn3ActionPerformed

    private void option2Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2Btn3ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl5.setText("Incorrect, try again");// TODO add your handling code here:
    }//GEN-LAST:event_option2Btn3ActionPerformed

    private void option4Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4Btn3ActionPerformed
        counterCorrect = counterCorrect + 1;
        correctLbl.setText(String.valueOf(counterCorrect));
        outcomeLbl5.setText("Correct");// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_option4Btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckBtn;
    private javax.swing.JLabel correctLbl;
    private javax.swing.JLabel incorrectLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton option1Btn;
    private javax.swing.JButton option1Btn1;
    private javax.swing.JButton option1Btn2;
    private javax.swing.JButton option1Btn3;
    private javax.swing.JButton option2Btn;
    private javax.swing.JButton option2Btn1;
    private javax.swing.JButton option2Btn2;
    private javax.swing.JButton option2Btn3;
    private javax.swing.JButton option3Btn;
    private javax.swing.JButton option3Btn1;
    private javax.swing.JButton option3Btn2;
    private javax.swing.JButton option3Btn3;
    private javax.swing.JButton option4Btn;
    private javax.swing.JButton option4Btn1;
    private javax.swing.JButton option4Btn2;
    private javax.swing.JButton option4Btn3;
    private javax.swing.JLabel outcomeLbl1;
    private javax.swing.JLabel outcomeLbl2;
    private javax.swing.JLabel outcomeLbl3;
    private javax.swing.JLabel outcomeLbl4;
    private javax.swing.JLabel outcomeLbl5;
    private javax.swing.JSpinner userInput1;
    // End of variables declaration//GEN-END:variables
}
