/*
 * Dylan Moore 
 * Oct 2 2019
 * Basic multiple choice quiz
 */

/**
 *
 * @author dymoo6791
 */
public class Page1 extends javax.swing.JFrame {

    /**
     * Creates new form Page1
     */
    public Page1() {
        initComponents();
    }
    int counterCorrect = 0; //set base value for correct counter
    int incorrectCounter = 0;//set base value for incorrect counter
    double percent = 0;//set base value for percent correct

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        correctLbl = new javax.swing.JLabel();
        userInput1 = new javax.swing.JSpinner();
        outcomeLbl1 = new javax.swing.JLabel();
        CheckBtn = new javax.swing.JButton();
        incorrectLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        outcomeLbl2 = new javax.swing.JLabel();
        option1Btn = new javax.swing.JButton();
        option3Btn = new javax.swing.JButton();
        option2Btn = new javax.swing.JButton();
        option4Btn = new javax.swing.JButton();
        option1Btn1 = new javax.swing.JButton();
        option3Btn1 = new javax.swing.JButton();
        option4Btn1 = new javax.swing.JButton();
        option2Btn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        outcomeLbl3 = new javax.swing.JLabel();
        outcomeLbl4 = new javax.swing.JLabel();
        option1Btn2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        option3Btn2 = new javax.swing.JButton();
        option2Btn2 = new javax.swing.JButton();
        option4Btn2 = new javax.swing.JButton();
        option3Btn3 = new javax.swing.JButton();
        option1Btn3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        option2Btn3 = new javax.swing.JButton();
        option4Btn3 = new javax.swing.JButton();
        outcomeLbl5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        percentLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Multiple Choice Quiz");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("How many math operators are used in programming?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        correctLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        correctLbl.setText("0");
        jPanel1.add(correctLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 40, 40, -1));

        userInput1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(userInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 83, 37));
        jPanel1.add(outcomeLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 184, 43));

        CheckBtn.setText("Check");
        CheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 108, -1, -1));

        incorrectLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        incorrectLbl.setText("0");
        jPanel1.add(incorrectLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 40, 38, -1));

        jLabel3.setText("Correct:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 20, -1, -1));

        jLabel4.setText("Incorrect:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Compiled Java source code is called");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, -1));
        jPanel1.add(outcomeLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 354, 184, 43));

        option1Btn.setText("Machine code");
        option1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1BtnActionPerformed(evt);
            }
        });
        jPanel1.add(option1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        option3Btn.setText("Bytecode");
        option3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3BtnActionPerformed(evt);
            }
        });
        jPanel1.add(option3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 313, -1, -1));

        option2Btn.setText("Compiled code");
        option2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2BtnActionPerformed(evt);
            }
        });
        jPanel1.add(option2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        option4Btn.setText("Source code");
        option4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4BtnActionPerformed(evt);
            }
        });
        jPanel1.add(option4Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        option1Btn1.setText("Algorithm");
        option1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1Btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(option1Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 260, -1, -1));

        option3Btn1.setText("Package");
        option3Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3Btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(option3Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 313, 80, -1));

        option4Btn1.setText("Java Application");
        option4Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4Btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(option4Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 313, -1, -1));

        option2Btn1.setText("Argument");
        option2Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2Btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(option2Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Which is a set of steps that tell how to solve a problem?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 214, -1, -1));
        jPanel1.add(outcomeLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 354, 184, 43));
        jPanel1.add(outcomeLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 543, 184, 43));

        option1Btn2.setText("int arr[] = new int(3);");
        option1Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1Btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(option1Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 449, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("How do you instantiate an array in Java?");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 403, -1, -1));

        option3Btn2.setText("int arr() = new int(3);");
        option3Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3Btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(option3Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        option2Btn2.setText("int arr[];");
        option2Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2Btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(option2Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 90, -1));

        option4Btn2.setText(" int arr[] = new int[3];");
        option4Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4Btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(option4Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, -1));

        option3Btn3.setText("11");
        option3Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3Btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(option3Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 502, -1, -1));

        option1Btn3.setText("15");
        option1Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1Btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(option1Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 449, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText(" Assuming int is of 4bytes, what is the size of int arr[15];?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 403, -1, -1));

        option2Btn3.setText("19");
        option2Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2Btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(option2Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 449, -1, -1));

        option4Btn3.setText("60");
        option4Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4Btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(option4Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 502, -1, -1));
        jPanel1.add(outcomeLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 536, 184, 43));

        jLabel9.setText("Percentage");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 20, -1, -1));

        percentLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        percentLbl.setText("0");
        jPanel1.add(percentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 40, 73, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option4Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4Btn3ActionPerformed
        counterCorrect = counterCorrect + 1; //add 1 to correct counter when button pressed
        correctLbl.setText(String.valueOf(counterCorrect)); //display new total
        outcomeLbl5.setText("Correct"); //outcome display
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100; //get percent
        percent = percent * 100;
        percent = Math.round(percent); // round to 2 decimals
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));//update percentage
    }//GEN-LAST:event_option4Btn3ActionPerformed

    private void option2Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2Btn3ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl5.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option2Btn3ActionPerformed

    private void option1Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1Btn3ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl5.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option1Btn3ActionPerformed

    private void option3Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3Btn3ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl5.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option3Btn3ActionPerformed

    private void option4Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4Btn2ActionPerformed
        counterCorrect = counterCorrect + 1;
        correctLbl.setText(String.valueOf(counterCorrect));
        outcomeLbl4.setText("Correct");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:  // TODO add your handling code here:
    }//GEN-LAST:event_option4Btn2ActionPerformed

    private void option2Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2Btn2ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl4.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option2Btn2ActionPerformed

    private void option3Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3Btn2ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl4.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option3Btn2ActionPerformed

    private void option1Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1Btn2ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl4.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option1Btn2ActionPerformed

    private void option2Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2Btn1ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl3.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option2Btn1ActionPerformed

    private void option4Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4Btn1ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl3.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option4Btn1ActionPerformed

    private void option3Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3Btn1ActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl3.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option3Btn1ActionPerformed

    private void option1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1Btn1ActionPerformed
        counterCorrect = counterCorrect + 1;
        correctLbl.setText(String.valueOf(counterCorrect));
        outcomeLbl3.setText("Correct");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option1Btn1ActionPerformed

    private void option4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4BtnActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl2.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));
    }//GEN-LAST:event_option4BtnActionPerformed

    private void option2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2BtnActionPerformed
        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl2.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));// TODO add your handling code here:
    }//GEN-LAST:event_option2BtnActionPerformed

    private void option3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3BtnActionPerformed
        counterCorrect = counterCorrect + 1;
        correctLbl.setText(String.valueOf(counterCorrect));
        outcomeLbl2.setText("Correct");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));
    }//GEN-LAST:event_option3BtnActionPerformed

    private void option1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1BtnActionPerformed

        incorrectCounter = incorrectCounter + 1;
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        incorrectLbl.setText(String.valueOf(incorrectCounter));
        outcomeLbl2.setText("Incorrect, try again");
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));
    }//GEN-LAST:event_option1BtnActionPerformed

    private void CheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBtnActionPerformed

        int Q1 = (Integer) userInput1.getValue();

        if (Q1 == 5) {
            outcomeLbl1.setText("Correct");
            counterCorrect = counterCorrect + 1;
            correctLbl.setText(String.valueOf(counterCorrect));
        } else {
            outcomeLbl1.setText("Incorrect, try again");
            incorrectCounter = incorrectCounter + 1;
            incorrectLbl.setText(String.valueOf(incorrectCounter));
        }
        percent = ((double) counterCorrect / (double) incorrectCounter) * 100;
        percent = percent * 100;
        percent = Math.round(percent);
        percent = percent / 100;
        percentLbl.setText(String.valueOf(percent));
    }//GEN-LAST:event_CheckBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckBtn;
    private javax.swing.JLabel correctLbl;
    private javax.swing.JLabel incorrectLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton option1Btn;
    private javax.swing.JButton option1Btn1;
    private javax.swing.JButton option1Btn2;
    private javax.swing.JButton option1Btn3;
    private javax.swing.JButton option2Btn;
    private javax.swing.JButton option2Btn1;
    private javax.swing.JButton option2Btn2;
    private javax.swing.JButton option2Btn3;
    private javax.swing.JButton option3Btn;
    private javax.swing.JButton option3Btn1;
    private javax.swing.JButton option3Btn2;
    private javax.swing.JButton option3Btn3;
    private javax.swing.JButton option4Btn;
    private javax.swing.JButton option4Btn1;
    private javax.swing.JButton option4Btn2;
    private javax.swing.JButton option4Btn3;
    private javax.swing.JLabel outcomeLbl1;
    private javax.swing.JLabel outcomeLbl2;
    private javax.swing.JLabel outcomeLbl3;
    private javax.swing.JLabel outcomeLbl4;
    private javax.swing.JLabel outcomeLbl5;
    private javax.swing.JLabel percentLbl;
    private javax.swing.JSpinner userInput1;
    // End of variables declaration//GEN-END:variables
}
